seed: ${trial_id}
trial_id: 0
project_name: bioseqgfn_al
version: v0.0.1

# Directories for loading and storing data
data_dir: /home/mila/m/moksh.jain/scratch/lambo
exp_name: test
group_name: somedetails
exp_tags: []
job_name: null
timestamp: ${now:%Y-%m-%d_%H-%M-%S}
log_dir: ${data_dir}/${exp_name}
wandb_mode: disabled
data_path: 'data/'

hydra:
  run:
    dir: ${log_dir}
  sweep:
    dir: ${log_dir}
    subdir: .

gfn:
  random_action_prob: 0.01
  max_len: 60
  min_len: 15
  batch_size: 128
  reward_exp: 8
  reward_min: 1e-80
  reward_max: 100
  sampling_temp: 1
  train_steps: 100
  pi_lr: 0.0001
  z_lr: 0.001
  wd: 0.0001
  gen_clip: 10
  sample_beta: 4
  eval_freq: 100
  k: 10
  num_samples: 128
  data_per_step: 16

  model:
    _target_: src.models.
    max_len: 60
    vocab_size: 26
    num_actions: 21
    num_hid: 256
    num_layers: 3
    num_head: 16
    dropout: 0
    batch_size: 128

proxy:
  _target_: src.models.
  proxy_learning_rate: 1e-5
  num_layers: 4
  dropout: 0.1
  num_hid: 1024
  L2: 1e-6
  batch_size: 
  early_stop_tol: 5
  train_steps: 100000
  num_dropout_samples: 25
  
  model: 
    _target_: src.models.
    max_len: 60
    vocab_size: 26
    num_actions: 21
    num_hid: 256
    num_layers: 3
    num_head: 16
    dropout: 0
    batch_size: 128